// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/17/2026, 11:35:49 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/workspaces/agriculturalmachinery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/plugins/**/*.{js,ts,mjs}","/workspaces/agriculturalmachinery/composables/**/*.{js,ts,mjs}","/workspaces/agriculturalmachinery/utils/**/*.{js,ts,mjs}","/workspaces/agriculturalmachinery/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/agriculturalmachinery/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["10"] = "/workspaces/agriculturalmachinery/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;